import {
  Award,
  BarChart3,
  Briefcase,
  Building2,
  Compass,
  FileText,
  Gavel,
  Globe,
  Handshake,
  Home,
  Key,
  Landmark,
  Layers,
  LayoutGrid,
  LineChart,
  Map,
  MapPin,
  MessageSquare,
  Package,
  Scale,
  Shield,
  ShieldCheck,
  Sparkles,
  Target,
  TrendingUp,
  Truck,
  Users,
  Zap,
} from 'lucide-react';

/** Icons the CMS lets editors choose from, by stable name. */
export const ICONS = {
  globe: Globe,
  building: Building2,
  home: Home,
  key: Key,
  'map-pin': MapPin,
  map: Map,
  compass: Compass,
  'trending-up': TrendingUp,
  'line-chart': LineChart,
  'bar-chart': BarChart3,
  briefcase: Briefcase,
  handshake: Handshake,
  users: Users,
  landmark: Landmark,
  scale: Scale,
  gavel: Gavel,
  shield: Shield,
  'shield-check': ShieldCheck,
  'file-text': FileText,
  layers: Layers,
  layout: LayoutGrid,
  package: Package,
  truck: Truck,
  target: Target,
  zap: Zap,
  award: Award,
  sparkles: Sparkles,
  message: MessageSquare,
};

export const ICON_NAMES = Object.keys(ICONS);

/** Social networks shown in the footer when a link is filled in. */
export const SOCIAL_NETWORKS = [
  ['linkedin', 'LinkedIn'],
  ['instagram', 'Instagram'],
  ['facebook', 'Facebook'],
  ['youtube', 'YouTube'],
  ['x', 'X (Twitter)'],
];

