// Generated by tools/optimize-assets.mjs. Do not edit by hand.
export default [
  {
    "id": "brand/icon-bird-jade",
    "group": "brand",
    "label": "Icon – bird, jade",
    "url": "/img/brand/icon-bird-jade-28a6df06.w512.webp",
    "width": 512,
    "height": 512,
    "widths": [
      256,
      512
    ],
    "kind": "image"
  },
  {
    "id": "brand/icon-globe-jade",
    "group": "brand",
    "label": "Icon – globe, jade",
    "url": "/img/brand/icon-globe-jade-f2b0633a.w512.webp",
    "width": 512,
    "height": 512,
    "widths": [
      256,
      512
    ],
    "kind": "image"
  },
  {
    "id": "brand/logo-condensed-jade",
    "group": "brand",
    "label": "Logo – condensed, jade",
    "url": "/img/brand/logo-condensed-jade-6ce74c90.w800.webp",
    "width": 800,
    "height": 320,
    "widths": [
      400,
      800
    ],
    "kind": "image"
  },
  {
    "id": "brand/logo-condensed-white",
    "group": "brand",
    "label": "Logo – condensed, white",
    "url": "/img/brand/logo-condensed-white-fea04b32.w800.webp",
    "width": 800,
    "height": 320,
    "widths": [
      400,
      800
    ],
    "kind": "image"
  },
  {
    "id": "brand/logo-horizontal-jade",
    "group": "brand",
    "label": "Logo – horizontal, jade",
    "url": "/img/brand/logo-horizontal-jade-0e2aa943.w960.webp",
    "width": 960,
    "height": 198,
    "widths": [
      480,
      960
    ],
    "kind": "image"
  },
  {
    "id": "brand/logo-horizontal-white",
    "group": "brand",
    "label": "Logo – horizontal, white",
    "url": "/img/brand/logo-horizontal-white-976bd80c.w960.webp",
    "width": 960,
    "height": 198,
    "widths": [
      480,
      960
    ],
    "kind": "image"
  },
  {
    "id": "brand/logo-main-beige",
    "group": "brand",
    "label": "Logo – main, beige",
    "url": "/img/brand/logo-main-beige-6930128b.w960.webp",
    "width": 960,
    "height": 549,
    "widths": [
      480,
      960
    ],
    "kind": "image"
  },
  {
    "id": "gallery/gallery-01",
    "group": "gallery",
    "label": "Gallery photo 01",
    "url": "/img/gallery/gallery-01-fce5859f.w1279.webp",
    "width": 1279,
    "height": 720,
    "widths": [
      640,
      1279
    ],
    "kind": "image"
  },
  {
    "id": "gallery/gallery-02",
    "group": "gallery",
    "label": "Gallery photo 02",
    "url": "/img/gallery/gallery-02-5eec9467.w1600.webp",
    "width": 1600,
    "height": 1066,
    "widths": [
      640,
      1280,
      1600
    ],
    "kind": "image"
  },
  {
    "id": "gallery/gallery-03",
    "group": "gallery",
    "label": "Gallery photo 03",
    "url": "/img/gallery/gallery-03-bf39008e.w1600.webp",
    "width": 1600,
    "height": 1066,
    "widths": [
      640,
      1280,
      1600
    ],
    "kind": "image"
  },
  {
    "id": "gallery/gallery-04",
    "group": "gallery",
    "label": "Gallery photo 04",
    "url": "/img/gallery/gallery-04-343e275f.w1600.webp",
    "width": 1600,
    "height": 1066,
    "widths": [
      640,
      1280,
      1600
    ],
    "kind": "image"
  },
  {
    "id": "gallery/gallery-05",
    "group": "gallery",
    "label": "Gallery photo 05",
    "url": "/img/gallery/gallery-05-a3bb76d9.w1600.webp",
    "width": 1600,
    "height": 1066,
    "widths": [
      640,
      1280,
      1600
    ],
    "kind": "image"
  },
  {
    "id": "gallery/gallery-06",
    "group": "gallery",
    "label": "Gallery photo 06",
    "url": "/img/gallery/gallery-06-9710d6d9.w1600.webp",
    "width": 1600,
    "height": 1066,
    "widths": [
      640,
      1280,
      1600
    ],
    "kind": "image"
  },
  {
    "id": "gallery/gallery-07",
    "group": "gallery",
    "label": "Gallery photo 07",
    "url": "/img/gallery/gallery-07-04caf760.w1066.webp",
    "width": 1066,
    "height": 1600,
    "widths": [
      640,
      1066
    ],
    "kind": "image"
  },
  {
    "id": "gallery/gallery-08",
    "group": "gallery",
    "label": "Gallery photo 08",
    "url": "/img/gallery/gallery-08-0419bdf0.w1600.webp",
    "width": 1600,
    "height": 1066,
    "widths": [
      640,
      1280,
      1600
    ],
    "kind": "image"
  },
  {
    "id": "gallery/gallery-09",
    "group": "gallery",
    "label": "Gallery photo 09",
    "url": "/img/gallery/gallery-09-06c77438.w1600.webp",
    "width": 1600,
    "height": 1066,
    "widths": [
      640,
      1280,
      1600
    ],
    "kind": "image"
  },
  {
    "id": "gallery/gallery-10",
    "group": "gallery",
    "label": "Gallery photo 10",
    "url": "/img/gallery/gallery-10-13ef906b.w1600.webp",
    "width": 1600,
    "height": 1066,
    "widths": [
      640,
      1280,
      1600
    ],
    "kind": "image"
  },
  {
    "id": "gallery/gallery-11",
    "group": "gallery",
    "label": "Gallery photo 11",
    "url": "/img/gallery/gallery-11-2c3295e3.w1066.webp",
    "width": 1066,
    "height": 1600,
    "widths": [
      640,
      1066
    ],
    "kind": "image"
  },
  {
    "id": "gallery/gallery-12",
    "group": "gallery",
    "label": "Gallery photo 12",
    "url": "/img/gallery/gallery-12-3eea4cae.w1600.webp",
    "width": 1600,
    "height": 1066,
    "widths": [
      640,
      1280,
      1600
    ],
    "kind": "image"
  },
  {
    "id": "gallery/gallery-13",
    "group": "gallery",
    "label": "Gallery photo 13",
    "url": "/img/gallery/gallery-13-1e360044.w1600.webp",
    "width": 1600,
    "height": 1066,
    "widths": [
      640,
      1280,
      1600
    ],
    "kind": "image"
  },
  {
    "id": "gallery/gallery-14",
    "group": "gallery",
    "label": "Gallery photo 14",
    "url": "/img/gallery/gallery-14-c51f6f89.w1600.webp",
    "width": 1600,
    "height": 1066,
    "widths": [
      640,
      1280,
      1600
    ],
    "kind": "image"
  },
  {
    "id": "gallery/gallery-15",
    "group": "gallery",
    "label": "Gallery photo 15",
    "url": "/img/gallery/gallery-15-104d69f4.w1600.webp",
    "width": 1600,
    "height": 1066,
    "widths": [
      640,
      1280,
      1600
    ],
    "kind": "image"
  },
  {
    "id": "gallery/gallery-16",
    "group": "gallery",
    "label": "Gallery photo 16",
    "url": "/img/gallery/gallery-16-01af1879.w1066.webp",
    "width": 1066,
    "height": 1600,
    "widths": [
      640,
      1066
    ],
    "kind": "image"
  },
  {
    "id": "gallery/gallery-17",
    "group": "gallery",
    "label": "Gallery photo 17",
    "url": "/img/gallery/gallery-17-6851ad48.w1600.webp",
    "width": 1600,
    "height": 1066,
    "widths": [
      640,
      1280,
      1600
    ],
    "kind": "image"
  },
  {
    "id": "gallery/gallery-18",
    "group": "gallery",
    "label": "Gallery photo 18",
    "url": "/img/gallery/gallery-18-0f04ff2b.w1600.webp",
    "width": 1600,
    "height": 1066,
    "widths": [
      640,
      1280,
      1600
    ],
    "kind": "image"
  },
  {
    "id": "gallery/gallery-19",
    "group": "gallery",
    "label": "Gallery photo 19",
    "url": "/img/gallery/gallery-19-636c3f6e.w1600.webp",
    "width": 1600,
    "height": 1066,
    "widths": [
      640,
      1280,
      1600
    ],
    "kind": "image"
  },
  {
    "id": "gallery/gallery-20",
    "group": "gallery",
    "label": "Gallery photo 20",
    "url": "/img/gallery/gallery-20-2cbcc152.w1600.webp",
    "width": 1600,
    "height": 1066,
    "widths": [
      640,
      1280,
      1600
    ],
    "kind": "image"
  },
  {
    "id": "gallery/gallery-21",
    "group": "gallery",
    "label": "Gallery photo 21",
    "url": "/img/gallery/gallery-21-9f8c958e.w1600.webp",
    "width": 1600,
    "height": 1066,
    "widths": [
      640,
      1280,
      1600
    ],
    "kind": "image"
  },
  {
    "id": "gallery/gallery-22",
    "group": "gallery",
    "label": "Gallery photo 22",
    "url": "/img/gallery/gallery-22-a464ed70.w1600.webp",
    "width": 1600,
    "height": 1066,
    "widths": [
      640,
      1280,
      1600
    ],
    "kind": "image"
  },
  {
    "id": "gallery/gallery-23",
    "group": "gallery",
    "label": "Gallery photo 23",
    "url": "/img/gallery/gallery-23-ef9b8601.w1600.webp",
    "width": 1600,
    "height": 1066,
    "widths": [
      640,
      1280,
      1600
    ],
    "kind": "image"
  },
  {
    "id": "gallery/gallery-24",
    "group": "gallery",
    "label": "Gallery photo 24",
    "url": "/img/gallery/gallery-24-725b91ee.w1600.webp",
    "width": 1600,
    "height": 899,
    "widths": [
      640,
      1280,
      1600
    ],
    "kind": "image"
  },
  {
    "id": "hero/hero-poster",
    "group": "hero",
    "label": "Home video – poster frame",
    "url": "/img/hero/hero-poster-1b8f795b.w1920.webp",
    "width": 1920,
    "height": 1080,
    "widths": [
      640,
      1280,
      1920
    ],
    "kind": "image"
  },
  {
    "id": "hero/hero-video",
    "group": "hero",
    "label": "Home video – San Francisco",
    "url": "/img/hero/hero-video-65a91d03.w1920.mp4",
    "width": 1920,
    "height": 1080,
    "widths": [
      1280,
      1920
    ],
    "kind": "video"
  },
  {
    "id": "partners/california-hispanic-chambers",
    "group": "partners",
    "label": "California Hispanic Chambers of Commerce",
    "url": "/img/partners/california-hispanic-chambers-14ceae04.w600.webp",
    "width": 600,
    "height": 231,
    "widths": [
      300,
      600
    ],
    "kind": "image"
  },
  {
    "id": "partners/cusmex",
    "group": "partners",
    "label": "CUSMEX",
    "url": "/img/partners/cusmex-86a9ed65.w600.webp",
    "width": 600,
    "height": 600,
    "widths": [
      300,
      600
    ],
    "kind": "image"
  },
  {
    "id": "partners/doots-international",
    "group": "partners",
    "label": "DOOTS International",
    "url": "/img/partners/doots-international-81235005.w321.webp",
    "width": 321,
    "height": 127,
    "widths": [
      300,
      321
    ],
    "kind": "image"
  },
  {
    "id": "partners/intelink-law-group",
    "group": "partners",
    "label": "Intelink Law Group",
    "url": "/img/partners/intelink-law-group-f034d1b5.w600.webp",
    "width": 600,
    "height": 213,
    "widths": [
      300,
      600
    ],
    "kind": "image"
  },
  {
    "id": "partners/intelink-law-group-white",
    "group": "partners",
    "label": "Intelink Law Group (white)",
    "url": "/img/partners/intelink-law-group-white-b7d5df50.w600.webp",
    "width": 600,
    "height": 213,
    "widths": [
      300,
      600
    ],
    "kind": "image"
  },
  {
    "id": "partners/our-billion-ventures",
    "group": "partners",
    "label": "Our Billion Ventures",
    "url": "/img/partners/our-billion-ventures-3833f9c8.w400.webp",
    "width": 400,
    "height": 400,
    "widths": [
      300,
      400
    ],
    "kind": "image"
  },
  {
    "id": "properties/176-randall-street-1",
    "group": "properties",
    "label": "176 Randall Street – street view",
    "url": "/img/properties/176-randall-street-1-7de043cc.w1920.webp",
    "width": 1920,
    "height": 1072,
    "widths": [
      640,
      1280,
      1920
    ],
    "kind": "image"
  },
  {
    "id": "properties/176-randall-street-2",
    "group": "properties",
    "label": "176 Randall Street – rear terraces",
    "url": "/img/properties/176-randall-street-2-5eaca185.w1920.webp",
    "width": 1920,
    "height": 1072,
    "widths": [
      640,
      1280,
      1920
    ],
    "kind": "image"
  },
  {
    "id": "properties/176-randall-street-3",
    "group": "properties",
    "label": "176 Randall Street – facade",
    "url": "/img/properties/176-randall-street-3-6edfb56b.w1920.webp",
    "width": 1920,
    "height": 1072,
    "widths": [
      640,
      1280,
      1920
    ],
    "kind": "image"
  },
  {
    "id": "services/advisory-office",
    "group": "services",
    "label": "Advisory office",
    "url": "/img/services/advisory-office-5e6bfaa7.w1024.webp",
    "width": 1024,
    "height": 1024,
    "widths": [
      640,
      1024
    ],
    "kind": "image"
  },
  {
    "id": "services/boardroom",
    "group": "services",
    "label": "Boardroom",
    "url": "/img/services/boardroom-0d88c069.w1024.webp",
    "width": 1024,
    "height": 1024,
    "widths": [
      640,
      1024
    ],
    "kind": "image"
  },
  {
    "id": "services/executive-office",
    "group": "services",
    "label": "Executive office",
    "url": "/img/services/executive-office-ac222db5.w1024.webp",
    "width": 1024,
    "height": 1024,
    "widths": [
      640,
      1024
    ],
    "kind": "image"
  },
  {
    "id": "services/global-network",
    "group": "services",
    "label": "Global network",
    "url": "/img/services/global-network-8ad3fea8.w1024.webp",
    "width": 1024,
    "height": 1024,
    "widths": [
      640,
      1024
    ],
    "kind": "image"
  },
  {
    "id": "services/hillside-residence",
    "group": "services",
    "label": "Hillside residence",
    "url": "/img/services/hillside-residence-248ca253.w1024.webp",
    "width": 1024,
    "height": 1024,
    "widths": [
      640,
      1024
    ],
    "kind": "image"
  },
  {
    "id": "services/legal-meeting",
    "group": "services",
    "label": "Legal meeting",
    "url": "/img/services/legal-meeting-ad5220db.w1024.webp",
    "width": 1024,
    "height": 1024,
    "widths": [
      640,
      1024
    ],
    "kind": "image"
  },
  {
    "id": "services/modern-residence",
    "group": "services",
    "label": "Modern residence",
    "url": "/img/services/modern-residence-615853e5.w1024.webp",
    "width": 1024,
    "height": 1024,
    "widths": [
      640,
      1024
    ],
    "kind": "image"
  },
  {
    "id": "services/office-campus",
    "group": "services",
    "label": "Office campus",
    "url": "/img/services/office-campus-bbb0f1f0.w1024.webp",
    "width": 1024,
    "height": 1024,
    "widths": [
      640,
      1024
    ],
    "kind": "image"
  },
  {
    "id": "services/port-at-dusk",
    "group": "services",
    "label": "Port at dusk",
    "url": "/img/services/port-at-dusk-8ac2b895.w1024.webp",
    "width": 1024,
    "height": 1024,
    "widths": [
      640,
      1024
    ],
    "kind": "image"
  },
  {
    "id": "services/supply-chain-port",
    "group": "services",
    "label": "Container port",
    "url": "/img/services/supply-chain-port-ccc86bc3.w1024.webp",
    "width": 1024,
    "height": 1024,
    "widths": [
      640,
      1024
    ],
    "kind": "image"
  },
  {
    "id": "services/tower-blueprint",
    "group": "services",
    "label": "Tower blueprint",
    "url": "/img/services/tower-blueprint-bf5d1df7.w1024.webp",
    "width": 1024,
    "height": 1024,
    "widths": [
      640,
      1024
    ],
    "kind": "image"
  },
  {
    "id": "team/elena-and-eduardo",
    "group": "team",
    "label": "Elena & Eduardo",
    "url": "/img/team/elena-and-eduardo-35f2dcb9.w960.webp",
    "width": 960,
    "height": 960,
    "widths": [
      480,
      960
    ],
    "kind": "image"
  },
  {
    "id": "team/keith-ismael",
    "group": "team",
    "label": "Keith Ismael",
    "url": "/img/team/keith-ismael-efe8aebf.w920.webp",
    "width": 920,
    "height": 1024,
    "widths": [
      480,
      920
    ],
    "kind": "image"
  },
  {
    "id": "team/ron-torres",
    "group": "team",
    "label": "Ron Torres",
    "url": "/img/team/ron-torres-001b2131.w960.webp",
    "width": 960,
    "height": 960,
    "widths": [
      480,
      960
    ],
    "kind": "image"
  },
  {
    "id": "team/victor-marquez",
    "group": "team",
    "label": "Victor M. Marquez",
    "url": "/img/team/victor-marquez-51ff85ab.w960.webp",
    "width": 960,
    "height": 960,
    "widths": [
      480,
      960
    ],
    "kind": "image"
  }
];
